Document: acpi-volumed
Title: Debian acpi-volumed Manual
Author: <insert document author here>
Abstract: This manual describes what acpi-volumed is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/acpi-volumed/acpi-volumed.sgml.gz

Format: postscript
Files: /usr/share/doc/acpi-volumed/acpi-volumed.ps.gz

Format: text
Files: /usr/share/doc/acpi-volumed/acpi-volumed.text.gz

Format: HTML
Index: /usr/share/doc/acpi-volumed/html/index.html
Files: /usr/share/doc/acpi-volumed/html/*.html
